tunnel: f776bf48-0d24-4520-b785-a03795c75e7e
credentials-file: /etc/cloudflared/creds/credentials.json
protocol: http2

ingress:
  - hostname: droppr.coolmri.com
    service: http://droppr:80
    originRequest:
      noTLSVerify: true

  - service: http_status:404
